
export const DAYS_FILTER = "DAYS_FILTER";
export const GET_FREE_VENUES = "GET_FREE_VENUES";
export const GET_ROOM = "GET_ROOM";
export const GET_ROOMS = "GET_ROOMS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_SIMILAR_ROOMS = "GET_SIMILAR_ROOMS";
export const SET_REMINDER = "SET_REMINDER";
export const GET_EXAMS = "GET_EXAMS";
export const GET_GROUPS = "GET_GROUPS"; 
export const SEARCH_VENUES = "SEARCH_VENUES";
export const FILTER_VENUES = "FILTER_VENUES";
export const FILTER_VENUE = "FILTER_VENUE";
export const GET_FREE_VENUE_SESSIONS = "GET_FREE_VENUE_SESSIONS"
