export const SET_CURRENT = "SET_CURRENT";
export const SET_ERRORS = "SET_ERRORS";
export const SET_ACTIVE_DAY = "SET_ACTIVE_DAY";
export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const DAYS_FILTER = "DAYS_FILTER";
export const SET_LOADING = "SET_LOADING";
export const SET_REMINDER = "SET_REMINDER";
export const SET_SHOW_MODEL = "SET_SHOW_MODEL";

export const GET_ROOM = "GET_ROOM";
export const GET_ROOMS = "GET_ROOMS";
export const GET_SIMILAR_ROOMS = "GET_SIMILAR_ROOMS";

export const GET_EXAMS = "GET_EXAMS";
export const GET_GROUPS = "GET_GROUPS";
export const SET_CURRENT_EXAMS = "SET_CURRENT_EXAMS";
export const SET_CURRENT_GROUPS = "SET_CURRENT_GROUPS";

export const GET_FREE_VENUES = "GET_FREE_VENUES";
export const SEARCH_VENUES = "SEARCH_VENUES";
export const FILTER_VENUES = "FILTER_VENUES";
export const FILTER_VENUE = "FILTER_VENUE";
export const GET_FREE_VENUE_SESSIONS = "GET_FREE_VENUE_SESSIONS";
export const OCCUPY_VENUE = "OCCUPY_VENUE";
export const RESET_OCCUPIED_TO_FREE = "RESET_OCCUPIED_TO_FREE";
export const SCHEDULE_FREEING_VENUE = "SCHEDULE_FREEING_VENUE";

export const GET_OLDEST_NOTIFICATIONS = "GET_OLDEST_NOTIFICATIONS";
export const GET_RECENT_NOTIFICATIONS = "GET_RECENT_NOTIFICATIONS";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const FILTER_NOTIFICATIONS = "FILTER_NOTIFICATIONS";

export const GET_INFO = "GET_INFO";

export const IS_LOADED = "IS_LOADED";
export const LOAD_USER = "LOAD_USER";
export const GET_USER = "GET_USER";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGOUT = "LOGOUT";
